repos:
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 25.1.0
- hooks:
  - args:
    - --fix
    id: ruff
  repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.12.2
- hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
